backend/controllers/ContentPagesController.php
<?php

namespace backend\controllers;

use common\components\controllers\page\BaseController;
use common\models\db\ContentPages;
use League\Uri\Components\Query;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;

class ContentPagesController extends BaseController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }


    public function beforeAction($action)
    {
//        AssetManager::register('site');
        return parent::beforeAction($action);
    }

    public function actionCreate()
    {
        $model = new ContentPages();
        if($model->load(Yii::$app->request->post()) && $model->save()){
	        $this->notifications->setNotifications($this->notifications->success, 'Страница "'.$model->title.'" успешно создана.');
            return $this->redirect(['index']);
        }else{
            $parent_pages = ContentPages::find()
                ->select('id, title')
                ->where(['id_parent' => 0])
                ->andWhere(['status' => 1])
                ->asArray()->all();

            $parent_pages = [0 => 'Без вложенности'] + ArrayHelper::map($parent_pages, 'id', 'title');

            return $this->render('create', [
                'model' => $model,
                'parents' => $parent_pages
            ]);
        }
    }

    public function actionDelete($id)
    {
        $model = ContentPages::find()
            ->where(['id' => $id])
            ->andWhere(['can_delete' => 1])
            ->one();

	    if (!$model->delete()) {
		    $this->notifications->setNotifications($this->notifications->error, 'Произошла ошибка. Попробуйте позже.');
	    }
	    $this->notifications->setNotifications($this->notifications->success, 'Страница "'.$model->title.'" успешно удалена.');
        return $this->redirect(['index']);
    }

    public function actionIndex()
    {
        $contentPages = ContentPages::find()->orderBy('id')->all();

        return $this->render('index',[
            'contentPages' => $contentPages
        ]);
    }

    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');
        $model = ContentPages::find()
            ->where(['id' => $id])
            ->one();

        if($model->load(Yii::$app->request->post())){
            if($model->update() !== false){
	            $this->notifications->setNotifications($this->notifications->success, 'Страница "'.$model->title.'" успешно обновлена.');
                return $this->redirect(['index']);
            }
        }else if(Yii::$app->request->get()){
            $parent_pages = ContentPages::find()
                ->select('id, title')
//                ->where(['id_parent' => 0])
                ->andWhere(['!=', 'id', $id])
                ->andWhere(['status' => 1])
                ->asArray()->all();

            $parent_pages = [0 => 'Без вложенности'] + ArrayHelper::map($parent_pages, 'id', 'title');

            return $this->render('update', [
                'model' => $model,
                'parents' => $parent_pages
            ]);
        }else{
            throw new NotFoundHttpException('Page not found');
        }
    }

}

backend/views/content-pages/_form.php
<?php
use common\models\db\ContentPages;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<form role="form" action="<?= Url::to() ?>" method="POST" class="form-horizontal form-groups-bordered">
    <div class="panel-body">
        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Название</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="title" name="<?= Html::getInputName($model, 'title') ?>" value="<?= $model->title ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Заголовок страницы</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="h1" name="<?= Html::getInputName($model, 'h1') ?>" value="<?= $model->h1 ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Описание</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="description" name="<?= Html::getInputName($model, 'description') ?>" value="<?= $model->description ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Ключевые слова</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="keywords" name="<?= Html::getInputName($model, 'keywords') ?>" value="<?= $model->keywords ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="w0" class="col-sm-4 control-label">Контент</label>
            <div class="col-sm-8">
                <?= yii\imperavi\Widget::widget([
                    'model' => $model,
                    'attribute' => 'content',
                    'options' => [
                        'lang' => 'ru',
                        'imageUpload' => Yii::$app->urlManager->createUrl(['/file-storage/upload-imperavi']),
                        'minHeight' => 300
                    ],
                ]) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Опубликовать страницу</label>
            <div class="col-sm-8">
                <?= Html::checkbox(Html::getInputName($model, 'status'), $model->status)?>
            </div>
        </div>

        <?=Html::hiddenInput(Html::getInputName($model, 'can_delete'), $model->can_delete)?>


        <div class="form-group">
            <label for="action" class="col-sm-4 control-label">Ссылка страницы</label>
            <div class="col-sm-8">
                <input <?=$model->can_delete ? '' : 'disabled'?> type="text" maxlength="255" class="form-control" id="action"
                       name="<?= Html::getInputName($model, 'action')?>"
                value="<?=$model->action?>">

            </div>
        </div>
        
        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Вложенность</label>
            <div class="col-sm-8">
                <?php echo Html::activeDropDownList($model, 'id_parent', $parents, [
                    'class' => 'selectboxit',
                ]);?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-12 text-right">
                <button class="btn btn-primary" type="submit"><?= $model->isNewRecord ? 'Создать' : 'Обновить' ?></button>
                <a href="<?=Url::to(['/content-pages']);?>" class="btn btn-danger">Отмена</a>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</form>

backend/views/content-pages/create.php
<?php
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Создание страницы";
$this->params['breadcrumbs'][] = [
	'label'=> 'Контент',
	'url' => Url::to(['/content-pages']),
	'itemprop' => 'url',
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
	<div class="col-md-12">
		<?= Breadcrumbs::widget([
			'homeLink' => [
				'label' => 'Главная',
				'url' => Yii::$app->getHomeUrl(),
				'itemprop' => 'url',
			],
			'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		]);?>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<h1><?=$this->title?></h1>
	</div>
</div>
<br/>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <h3>Новая страница</h3>
                </div>
            </div>
            <?= $this->render('_form', [
                'model' => $model,
                'parents' => $parents
            ]) ?>
        </div>
    </div>
</div>

backend/views/content-pages/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

$this->title = 'Контент';
$this->params['breadcrumbs'][] = $this->title;

?>


<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-6">
        <div class="row">
            <div class="col-md-12">
                <?= Breadcrumbs::widget([
					'homeLink' => [
						'label' => 'Главная',
						'url' => Yii::$app->getHomeUrl(),
						'itemprop' => 'url',
					],
					'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],]);?>
            </div>
        </div>
        <div class="row">
			<div class="col-md-8 col-sm-8 col-xs-8">
				<h1><?=$this->title?></h1>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-4 text-right">
				<br/>
				<a class="btn btn-success btn-lg btn-icon icon-left" href="<?= Url::to(['content-pages/create']); ?>">Добавить страницу<i class="entypo-plus"></i></a>
			</div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-12">
                <?php if (count($contentPages) > 0): ?>
                <table class="table table-striped table-bordered table-hover text-center font-size-16 responsive">
                    <thead>
                        <tr class="row ">
                            <th>H1</th>
							<th>Создана / Обновлена</th>
							<th>Статус</th>
							<th width="1%">Действия</th>
						</tr>
                    </thead>
                    <tbody>
                    <?php foreach($contentPages as $page): ?>
                        <tr class="row">
                            <td class="middle-align text-left">
								<a href="<?=Url::to(['content-pages/update', 'id' => $page->id]);?>">
									<?= Yii::$app->helpers->formattingProperty($page, 'h1')?>
								</a>
							</td>
							<td class="middle-align"><?= Yii::$app->helpers->formattingProperty($page, 'created_at')?></td>
							<td class="middle-align">
								<div class="label label-<?=$page->status ? 'success': 'default'?>">
									<?= Yii::$app->helpers->formattingProperty($page, 'status') ? 'Активная' : 'Неактивная'?>
								</div>
							</td>
                            <td class="middle-align">
								<nobr>
									<a class="btn btn-primary btn-lg" title="Редактировать" href="<?= Url::to(['content-pages/update', 'id' => $page->id]) ?>">
										<i class="entypo-pencil"></i>
									</a>
									<a class="btn btn-info btn-lg" target="_blank" title="Просмотреть" href="<?= Yii::getAlias('@frontendUrl').'/'.$page->action ?>">
										<i class="entypo-eye"></i>
									</a>
									<?php if($page->can_delete == 1): ?>
										<a class="btn btn-danger btn-lg" title="Удалить" href="<?= Url::to(['content-pages/delete', 'id' => $page->id]) ?>">
											<i class="entypo-cancel"></i>
										</a>
									<?php endif;?>
								</nobr>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else:?>
                    <div class="row">
                        <div class="col-md-12 alert alert-info">
                            <h3>Не создано ни одной страницы!</h3>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>

backend/views/content-pages/update.php
<?php
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = $model->h1;
$this->params['breadcrumbs'][] = [
	'label'=> 'Контент',
	'url' => Url::to(['/content-pages']),
	'itemprop' => 'url',
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
	<div class="col-md-12">
		<?= Breadcrumbs::widget([
			'homeLink' => [
				'label' => 'Главная',
				'url' => Yii::$app->getHomeUrl(),
				'itemprop' => 'url',
			],
			'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		]);?>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<h1><?=$this->title?></h1>
	</div>
</div>
<br/>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <h3>Редактировать страницу</h3>
                </div>
            </div>
            <?= $this->render('_form', [
                'model' => $model,
                'parents' => $parents
            ]) ?>
        </div>
    </div>
</div>