backend/controllers/BlogController.php
<?php
namespace backend\controllers;


use backend\components\controllers\page\BaseController;
use common\models\db\Blog;
use common\models\db\ContentPages;
use yii\data\ActiveDataProvider;
use yii\web\BadRequestHttpException;

class BlogController extends BaseController
{

    public function actionIndex(){

        $model = new ActiveDataProvider([
            'query' => Blog::find()
                ->orderBy(['published_at' => SORT_DESC]),
            'pagination' => [
                'pageSize' => 10
            ]
        ]);

        return $this->render('index', [
            'model' => $model
        ]);

    }

    public function actionUpdate($id){
        $model = Blog::find()
            ->where(['id' => $id])
            ->one();

        if($model === null){
            throw new BadRequestHttpException();
        }

        if(\Yii::$app->request->post()){
            if ($model->load(\Yii::$app->request->post()) && $model->save()) {
                $this->notifications->setNotifications($this->notifications->success, 'Запись "'.$model->title.'" успешно сохранена.');
                return $this->redirect(['/blog/index']);
            }else{
                $this->notifications->setNotifications($this->notifications->error, 'Ошибка сохранения записи "'.$model->title);
                return $this->render('update', [
                    'model' => $model
                ]);
            }
        }else{
            return $this->render('update', [
                'model' => $model
            ]);
        }
    }

    public function actionCreate(){
        $model = new Blog();

        if(\Yii::$app->request->post()){
            if ($model->load(\Yii::$app->request->post()) && $model->save()) {
                $this->notifications->setNotifications($this->notifications->success, 'Запись "'.$model->title.'" успешно сохранена.');
                return $this->redirect(['index']);
            }else{
                $this->notifications->setNotifications($this->notifications->error, 'Ошибка сохранения записи "'.$model->title);
                return $this->redirect('create');
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
}

frontend/controllers/BlogController.php
<?php

namespace frontend\controllers;

use common\components\controllers\page\BaseController;
use common\models\db\Blog;
use common\models\db\ContentPages;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;


class BlogController extends BaseController
{
    public function actionSlug(){

        $slug = Yii::$app->request->get('slug');

        $page = Blog::find()
            ->where(['status' => Blog::$STATUS_ACTIVE])
            ->andWhere(['action' => $slug])
            ->one();

        if($page == null){
            throw new NotFoundHttpException('Страница не найденна');
        }

        return $this->render('page', [
            'model' => $page
        ]);
    }

    public function actionIndex(){

        $blogPage = ContentPages::find()
            ->where(['action' => 'blog'])
            ->one();

        $pages = Blog::find()
            ->where(['status' => Blog::$STATUS_ACTIVE])
            ->orderBy(['published_at' => SORT_DESC]);
        
        $data = new ActiveDataProvider([
            'query' => $pages,
            'pagination' => [
                'pageSize' => 2
            ]
        ]);
        
        return $this->render('index', [
            'model' => $data,
            'blogPage' => $blogPage
        ]);
    }
}

backend/views/blog/_form.php
<?php
use trntv\filekit\widget\Upload;
use trntv\yii\datetime\DateTimeWidget;
use yii\helpers\Html;
use yii\helpers\Url;

//data-view-type="blog.BlogItem"
?>

<form role="form" action="<?= Url::to() ?>" method="POST" class="form-horizontal form-groups-bordered"
      id="blog-form">
    <div class="panel-body">
        <div class="form-group">
            <label for="h1" class="col-sm-4 control-label">Название</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="h1"
                       name="<?= Html::getInputName($model, 'h1') ?>" value="<?= $model->h1 ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="title" class="col-sm-4 control-label">Заголовок</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="title" name="<?= Html::getInputName($model, 'title') ?>"
                       value="<?= $model->title ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="w0" class="col-sm-4 control-label">Обложка</label>
            <div class="col-sm-8">
                <?= Upload::widget([
                    'model' => $model,
                    'attribute' => 'thumbnail',
                    'url' => ['/file-storage/upload'],
                    'maxFileSize' => 5000000, // 5 MiB
                ]) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Описание</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="description"
                       name="<?= Html::getInputName($model, 'description') ?>" value="<?= $model->description ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="field-1" class="col-sm-4 control-label">Ключевые слова</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="keywords"
                       name="<?= Html::getInputName($model, 'keywords') ?>" value="<?= $model->keywords ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="w0" class="col-sm-4 control-label">Контент</label>
            <div class="col-sm-8">
                <?= yii\imperavi\Widget::widget([
                    'model' => $model,
                    'attribute' => 'content',
                    'options' => [
                        'lang' => 'ru',
                        'imageUpload' => Yii::$app->urlManager->createUrl(['/file-storage/upload-imperavi']),
                        'minHeight' => 300
                    ],
                ]) ?>
            </div>
        </div>

        <div class="form-group">
            <div class="text-right col-sm-4">
                <label for="published_at" class="control-label label-bootstrap-height">Дата публикации: </label>
            </div>
            <div class="col-sm-8">
                <?= DateTimeWidget::widget([
                    'name' => Html::getInputName($model, 'published_at'),
                    'model' => $model,
                    'phpDatetimeFormat' => 'yyyy-MM-dd HH:mm',
                    'momentDatetimeFormat' => 'YYYY-MM-DD HH:mm:ss',
                    'clientOptions' => [
                        'format' => 'YYYY-MM-DD HH:mm:ss',
                        'allowInputToggle' => false,
                        'sideBySide' => true,
                        'locale' => 'ru-ru	',
                        'widgetPositioning' => [
                            'horizontal' => 'auto',
                            'vertical' => 'auto'
                        ],
                    ],
                    'options' => [
                        'class' => 'form-control discount-date'
                    ]
                ]); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="parent_id" class="col-sm-4 control-label">Статус</label>
            <div class="col-md-8 col-sm-6 col-xs-4">
                <select class="form-control" name="<?= Html::getInputName($model, 'status') ?>">
                    <?php $statusLabels = $model->getStatusLabel() ?>
                    <?php foreach ($statusLabels as $status => $label): ?>
                        <option <?= $model->status == $status ? 'selected' : '' ?>
                            value="<?= $status ?>"><?= $label ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="action" class="col-sm-4 control-label">Ссылка страницы</label>
            <div class="col-sm-8">
                <input disabled type="text" maxlength="255" class="form-control"
                       id="action"
                       value="<?= $model->action ?>">

            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-12 text-right">
                <button class="btn btn-primary"
                        type="submit"><?= $model->isNewRecord ? 'Создать' : 'Обновить' ?></button>
                <a href="<?= Url::to('/blog'); ?>" class="btn btn-danger">Отмена</a>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</form>

backend/views/blog/create.php
<?php
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

$this->title = 'Новая запись';
$this->params['breadcrumbs'][] = [
    'label' => 'Блог',
    'url' => Url::to(['/blog']),
    'itemprop' => 'url',
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="row">
    <div class="col-md-12">
        <?= Breadcrumbs::widget([
            'homeLink' => [
                'label' => 'Главная',
                'url' => Yii::$app->getHomeUrl(),
                'itemprop' => 'url',
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h1><?= $this->title ?></h1>
    </div>
</div>
<br/>


<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <h3>Создать запись</h3>
                </div>
            </div>

            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

backend/views/blog/index.php
<?php

use common\components\widgets\Pager;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

$this->title = 'Блог';
$this->params['breadcrumbs'][] = 'Контент';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="row">
    <div class="col-md-12 col-sm-12" data-view-type="blog.MainList">
        <div class="row">
            <div class="col-md-12">
                <?= Breadcrumbs::widget(['links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],]); ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-sm-8 col-xs-8">
                <h1><?= $this->title ?></h1>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4 text-right">
                <br/>
                <a class="btn btn-success btn-lg btn-icon icon-left" href="<?= Url::to(['blog/create']); ?>">
                    Добавить запись
                    <i class="entypo-plus"></i>
                </a>
            </div>
        </div>
        <br/>


        <div class="row">
            <div class="col-md-12 col-sm-12">
                <?php if (count($model->models) > 0): ?>
                    <table class="table table-striped table-bordered table-hover text-center font-size-16 responsive">
                        <thead>
                        <tr>
                            <th class="text-center">Заголовок</th>
                            <th class="text-center">Создана/Обновлена</th>
                            <th class="text-center">Опубликована</th>
                            <th class="text-center">Статус</th>
                            <th class="text-center">Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($model->models as $post): ?>
                            <tr>
                                <td class="middle-align"><?= Yii::$app->helpers->formattingProperty($post, 'title') ?></td>
                                <td class="middle-align">
                                    <?= $post->updated_at
                                        ? Yii::$app->helpers->formattingProperty($post, 'updated_at')
                                        : Yii::$app->helpers->formattingProperty($post, 'created_at')
                                    ?>
                                </td>
                                <td class="middle-align"><?= Yii::$app->helpers->formattingProperty($post, 'published_at') ?></td>
                                <td class="middle-align"><?= $post->getStatusLabel()[$post->status]?></td>
                                <td class="middle-align" data-id="<?= $post->id ?>">
                                    <nobr>
                                        <a title="Редактировать" class="btn btn-primary btn-lg"
                                           href="<?= Url::to(['blog/update', 'id' => $post->id]) ?>">
                                            <i class="entypo-pencil"></i>
                                        </a>
                                        <button title="Удалить" class="btn btn-danger btn-lg blog-delete-action">
                                            <i class="entypo-cancel"></i>
                                        </button>
                                    </nobr>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <div class="alert alert-info">
                        Записей не найдено
                    </div>
                <?php endif; ?>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6 ">
                Показано <?= $model->pagination->pageSize < $model->pagination->totalCount
                    ? $model->pagination->pageSize
                    : $model->pagination->totalCount ?> из <?= $model->pagination->totalCount ?> записей
            </div>
            <div class="col-md-6 text-right">
                <?= Pager::widget([
                    'pages' => $model->pagination,
                    'viewTemplate' => 'pager/backend'
                ]); ?>
            </div>
        </div>

    </div>
</div>


<?= \backend\widgets\ModalDialog::widget([
    'name'=>'model-delete',
    'title' => 'Удалить запись',
    'message' => 'Вы действительно хотите удалить запись блога?',
    'modalId' => 'blog-delete',
    'backBoneDataViewType' => 'modals.DeleteBlog'
])?>

backend/views/blog/update.php
<?php
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

$this->title = $model->title;
$this->params['breadcrumbs'][] = [
    'label' => 'Блог',
    'url' => Url::to(['/blog']),
    'itemprop' => 'url',
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="row">
    <div class="col-md-12">
        <?= Breadcrumbs::widget([
            'homeLink' => [
                'label' => 'Главная',
                'url' => Yii::$app->getHomeUrl(),
                'itemprop' => 'url',
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h1><?= $this->title ?></h1>
    </div>
</div>
<br/>


<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <h3>Редактировать запись</h3>
                </div>
            </div>

            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>