backend/controllers/BrandController.php
<?php

namespace backend\controllers;

use common\components\controllers\page\BaseController;
use common\models\db\Brand;
use yii\data\ActiveDataProvider;
use yii\web\BadRequestHttpException;

class BrandController extends BaseController
{
    public function actionCreate()
    {
        $model = new Brand();

        if(\Yii::$app->request->post()){
            if ($model->load(\Yii::$app->request->post()) && $model->save()) {
                $this->notifications->setNotifications($this->notifications->success, 'Бренд "'.$model->name.'" успешно сохранен.');
                return $this->redirect(['index']);
            }else{
                $this->notifications->setNotifications($this->notifications->error, 'Ошибка сохранения бренда');
                return $this->redirect('create');
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }


    public function actionIndex()
    {
        $brands = new ActiveDataProvider([
            'query' => Brand::find(),
            'pagination' => [
                'pageSize' => 10
            ]
        ]) ;

        return $this->render('index', [
			'brands' => $brands
		]);
    }

    public function actionUpdate($id)
    {
        $brand = Brand::find()
            ->where(['id' => $id])
            ->one();
        
        if($brand === null){
            throw new BadRequestHttpException();
        }

        $this->pageData['brand'] = $brand->toArray();
        if(\Yii::$app->request->post()){
            if ($brand->load(\Yii::$app->request->post()) && $brand->save()) {
                $this->notifications->setNotifications($this->notifications->success, 'Бренд "'.$brand->name.'" успешно сохранен.');
                return $this->redirect(['/brand']);
            }else{
                $this->notifications->setNotifications($this->notifications->error, 'Ошибка сохранения бренда "'.$brand->name);
                return $this->render('update', [
                    'model' => $brand
                ]);
            }
        }else{
            return $this->render('update', [
                'model' => $brand
            ]);
        }
    }

}

frontend/controllers/BrandController.php
<?php
/**
 * Created by PhpStorm.
 * User: bbyte
 * Date: 6/29/16
 * Time: 7:38 PM
 */

namespace frontend\controllers;


use common\components\controllers\page\BaseController;
use common\models\db\Brand;
use common\models\db\ContentPages;
use yii\data\Pagination;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;

class BrandController extends BaseController
{

    public function actionIndex(){

		$brandContent = ContentPages::findOne(['action'=>'brands']);
     
        $brands = Brand::find();

        $countc = clone $brands;
        $pages = new Pagination([
            'totalCount' => $countc->count(),
            'pageSize' => 6
        ]);
        $brands = $brands->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        
        if($brands === null){
            throw new NotFoundHttpException(); 
        }
        
        return $this->render('index', [
            'model' => $brands,
			'content' => $brandContent,
            'pages' => $pages
        ]);
    }
    
    public function actionSlug($slug){
        $model = Brand::find()
            ->where(['slug' => $slug])
            ->one();
        if (!$model) {
            throw new BadRequestHttpException();
        }

        return $this->render('view', [
			'model' => $model
		]);
    }
}

backend/views/brand/_form.php
<?php
use trntv\filekit\widget\Upload;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<form role="form" action="<?= Url::to() ?>" method="POST" class="form-horizontal form-groups-bordered"
data-view-type="brand.BrandItem" id="brand-form">
    <div class="panel-body">
        <div class="form-group">
            <label for="name" class="col-sm-4 control-label">Имя</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="name"
                       name="<?= Html::getInputName($model, 'name') ?>" value="<?= $model->name ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="h1" class="col-sm-4 control-label">Заголовок</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="h1" name="<?= Html::getInputName($model, 'h1') ?>" value="<?= $model->h1 ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="description" class="col-sm-4 control-label">Описание</label>
            <div class="col-sm-8">
                <textarea name="<?= Html::getInputName($model, 'description') ?>"
                          id="description" rows="4"
                          class="col-sm-12 form-control"><?= $model->description ?></textarea>
            </div>
        </div>

        <div class="form-group">
            <label for="w0" class="col-sm-4 control-label">Логотип</label>
            <div class="col-sm-8">
                <?= Upload::widget([
                    'model' => $model,
                    'attribute' => 'thumbnail',
                    'url' => ['/file-storage/upload'],
                    'maxFileSize' => 5000000, // 5 MiB
                ]) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label" for="<?=Html::getInputName($model, 'is_top_brand');?>">Показывать на главной</label>
            <div class="col-sm-8">
                <div class="checkbox">
                    <label>

                        <input type="checkbox" class="status-checkbox" <?= ($model->is_top_brand) ? 'checked': ''?>>
                        <input type="hidden"
                               name="<?=Html::getInputName($model, 'is_top_brand');?>"
                               class="status-input">
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="w0" class="col-sm-4 control-label">Контент</label>
            <div class="col-sm-8">
                <?= yii\imperavi\Widget::widget([
                    'model' => $model,
                    'attribute' => 'content',
                    'options' => [
                        'lang' => 'ru',
                    ],
                ]) ?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-md-12 text-right">
                <button class="btn btn-primary" type="submit"><?= $model->isNewRecord ? 'Создать' : 'Обновить' ?></button>
                <a href="<?=Url::to('/brand');?>" class="btn btn-danger">Отмена</a>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</form>

backend/views/brand/create.php
<?php

use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

$this->title = 'Создать бренд';
$this->params['breadcrumbs'][] = [
    'label'=> 'Бренды',
    'url' => Url::to(['/brand']),
    'itemprop' => 'url',
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="row">
    <div class="col-md-12">
        <?= Breadcrumbs::widget([
            'homeLink' => [
                'label' => 'Главная',
                'url' => Yii::$app->getHomeUrl(),
                'itemprop' => 'url',
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]);?>
    </div>
</div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <h3><?= $this->title ?></h3>
                </div>
            </div>
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

backend/views/brand/index.php
<?php
use common\components\widgets\Pager;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

$this->title = 'Бренды';
$this->params['breadcrumbs'][] = 'Каталог';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="row">
    <div class="col-md-12 col-sm-12" data-view-type="brand.MainList">
        <div class="row">
            <div class="col-md-12">
                <?= Breadcrumbs::widget(['links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],]);?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-sm-10 col-xs-10">
                <h1><?=$this->title?></h1>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 text-right">
                <br/>
                <a class="btn btn-success" href="<?= Url::to(['brand/create']); ?>">
                    <i class="entypo-plus"></i>
                </a>
            </div>
        </div>
        <br/>

        <div class="row">
            <div class="col-md-12 col-sm-12">
               <?php if(count($brands->models) > 0): ?>
                   <table class="table table-striped table-bordered table-hover text-center font-size-16 responsive">
                       <thead>
                       <tr>
                           <th class="text-center">Превью</th>
                           <th class="text-center">Название</th>
                           <th class="text-center">Заголовок</th>
                           <th class="text-center">Описание</th>
                           <th class="text-center">На главной?</th>
                           <th class="text-center">Действия</th>
                       </tr>
                       </thead>
                       <tbody>
                       <?php foreach ($brands->models as $brand): ?>
                           <tr>
                               <td class="middle-align"><img src="<?= Yii::$app->helpers->formattingProperty($brand, 'previewSrc')?>"
                                                             alt="<?=$brand->name ?>"></td>
                               <td class="middle-align"><?= Yii::$app->helpers->formattingProperty($brand, 'name') ?></td>
                               <td class="middle-align"><?= Yii::$app->helpers->formattingProperty($brand, 'h1') ?></td>
                               <td class="middle-align"><?= Yii::$app->helpers->formattingProperty($brand, 'description')?></td>
                               <td class="middle-align">
                                   <?php if($brand->is_top_brand == 1):?>
                                   <div class="label label-success"><i class="entypo-check"></i></div>
                                   <?php endif?>
                               </td>
                               <td class="middle-align" data-id="<?=$brand->id?>">
                                   <nobr>
                                       <a title="Редактировать" class="btn btn-primary" href="<?= Url::to(['brand/update', 'id' => $brand->id]) ?>">
                                           <i class="entypo-pencil"></i>
                                       </a>
                                       <button title="Удалить" class="btn btn-danger brand-delete-action">
                                           <i class="entypo-cancel"></i>
                                       </button>
                                   </nobr>
                               </td>
                           </tr>
                       <?php endforeach; ?>
                       </tbody>
                   </table>
                <?php else: ?>
                   <div class="alert alert-info">
                       Товаров не найдено
                   </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="row">
        <div class="col-md-6 ">
            Показано <?= $brands->pagination->pageSize < $brands->pagination->totalCount
                ? $brands->pagination->pageSize
                : $brands->pagination->totalCount ?> из <?= $brands->pagination->totalCount ?> записей
        </div>
        <div class="col-md-6 text-right">
            <?= Pager::widget([
                'pages' => $brands->pagination,
                'viewTemplate' => 'pager/backend'
            ]);	?>
        </div>
    </div>

    </div>
</div>


<?= \backend\widgets\ModalDialog::widget([
    'name'=>'model-delete',
    'title' => 'Удалить бренд',
    'message' => 'Вы действительно хотите удалить бренд?',
    'modalId' => 'brand-delete',
    'backBoneDataViewType' => 'modals.DeleteBrand'
])?>

backend/views/brand/update.php
<?php

use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

$this->title = $model->name;
$this->params['breadcrumbs'][] = [
    'label'=> 'Бренды',
    'url' => Url::to(['/brand']),
    'itemprop' => 'url',
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="row">
    <div class="col-md-12">
        <?= Breadcrumbs::widget([
            'homeLink' => [
                'label' => 'Главная',
                'url' => Yii::$app->getHomeUrl(),
                'itemprop' => 'url',
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]);?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h1><?=$this->title?></h1>
    </div>
</div>
<br/>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <h3>Редактировать бренд</h3>
                </div>
            </div>
            
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
        </div>
    </div>
</div>